---
- hosts: server-node
  remote_user: ansible
  vars:
    temp_folder: /tmp
  tasks:
    # Install prerequisites
    - include: tasks/prerequisites.yml
    
    # Install MongoDB
    - include: tasks/mongodb.yml

    # Install Node.js
    - include: tasks/nodejs.yml
