---
# File mongodb.yml
#
# Description: Install MongoDB
#
# OS Family: Ubuntu

- name: MongoDB | Import public key
  apt-key: keyserver=hkp://keyserver.ubuntu.com:80 --recv EA312927

- name: MongoDB | Add repository
  apt-repository:
    filename: /etc/apt/sources.list.d/mongodb-org-3.2.list
    repo: "http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse"
    state: present
    update_cache: yes

- name: MongoDB | Install MongoDB
  apt:
    name: mongodb-org
    state: present
    update_cache: yes

- name: MongoDB | Ensure that MongoDB is running
  service:
    name: mongod
    state: started
